### PR TITLE
support touch events

### PR DESCRIPTION
**Pull request by gross1989**

### CODE REVIEW

**Comment by larsblumberg** [comment]
Thanks @gross1989!

**Comment by naimo84** [comment]
Hey folks, hopefully not another noob question ;)
But what I've to todo, to get touch events working? I've already pulled the latest git-version, but no touch event appears. Swipe, Fly, Button, Rotate is working wonderful.

**Comment by gross1989** [comment]
For your controller to support all events including touch, it should say `discovered 16 characteristics` after connection.

**Comment by naimo84** [comment]
I only get 15 :(

INFO: connecting
INFO: connected
INFO: discovering characteristics
INFO: discovered 15 characteristics
INFO: enable_notification ROTATION
INFO: enable_notification FLY
INFO: enable_notification BUTTON
INFO: enable_notification SWIPE

**Comment by larsblumberg** [comment]
@naimo84 – no worries, it's all fine. Simple touch events will only be sent after we've rolled out the next firmware update. We've planned to ship it until next week, it will be version 2.3.0. Please let me know if you encounter any issues after updating the firmware.

**Pull request merged**
