### PR TITLE
received data is of type bytes instead of str in new version of pygat…

### PR DESCRIPTION
**Pull request by gross1989**
…tlib to prevent decode error in python3 (See commit https://bitbucket.org/OscarAcena/pygattlib/commits/9eed59747bbafc3e9afba0db9f32c4f6efd54beb)

### CODE REVIEW

**Comment by larsblumberg** [comment]
The SDK is already referencing the new version of pygattlib you're referring to, right?

**Comment by gross1989** [comment]
no, sadly the version in pip is older and the fork https://github.com/matthewelse/pygattlib also doesn't have the commit integrated

**Comment by larsblumberg** [comment]
But wouldn't your PR then break the Nuimo SDK if somebody doesn't use that version of pygattlib you make this change for?

**Comment by gross1989** [comment]
so I should update the README to refer to the repo in https://bitbucket.org/OscarAcena/pygattlib/

**Comment by larsblumberg** [comment]
Let me first check why we're using the fork on github at all and not the repo in bitbucket – I will come back to you with an answer.

**Comment by larsblumberg** [comment]
Are you actually using the bitbucket repo for pygattlib – does it work well for you?

**Comment by gross1989** [comment]
yes it work, the only difference is its a mercurial and not a git repository

**Comment by larsblumberg** [comment]
Since you and others report that https://bitbucket.org/OscarAcena/pygattlib/ is working more reliable, we should merge your PR. Can you please update the README as part of the PR to link that lib on bitbucket, please?

**Comment by larsblumberg** [comment]
Thanks @gross1989 – much appreciated!

**Pull request merged**
